[package]
name = "rust-edf"
version = "0.1.0"
authors = ["Maxime Leprince <maxime.leprince@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
chrono = "0.4.6"
serde = "1.0.89"
serde_derive = "1.0.89"
positioned-io-preview = "0.3.3"